---
title: "Frequency Distributions"
author: "Ernesto Diaz"
output: html_document
---

```{r}
# generates a random distribution of male and female age's 
set.seed(1000)
df = data.frame(
    gender=factor(rep(c('F', 'M'), each=200)),
    age=round(c(rnorm(200, mean=25, sd=5), rnorm(200, mean=30, sd=5))),
    hours=round(c(rnorm(200, mean=15, sd=10), rnorm(200, mean=30, sd=15)))
)
head(df)
```

```{r}
library(plyr)

# generates a simple frequency table for males and their respective age's
total_count = count(df[df$gender=='M',], 'age')
total_count
```

```{r}
library(ggplot2)

# plots a histogram for male age's
hist_plot = ggplot(df[df$gender=='M',], aes(x=age, fill=gender)) + geom_histogram(color='black', fill='lightblue', binwidth=2) + xlab('Age') + ylab('Count') + ggtitle('Distribution of Male Age\'s') + theme(plot.title = element_text(hjust = 0.5))
hist_plot
```

```{r}
# plots a frequency polygon for male age's
poly_plot = ggplot(df[df$gender=='M',], aes(x=age)) + geom_freqpoly(color='black', binwidth=2) + xlab('Age') + ylab('Count') + ggtitle('Distribution of Male Age\'s') + theme(plot.title = element_text(hjust = 0.5))
poly_plot
```

```{r}
# creates a box and whisker plot for male and female age's
box_and_whisker = ggplot(df, aes(x=age, y=gender)) + geom_boxplot(fill='lightblue', color='black') + xlab('Age') + ylab('Gender') + ggtitle('Age Distribution Between Males and Females') + theme(plot.title = element_text(hjust = 0.5))
box_and_whisker
```

```{r} 
bubble_graph = ggplot(df[df$age >= 15 & df$age <= 35,], aes(x=age, y=hours)) + geom_point(aes(color=gender, size=age), alpha=0.5) + scale_color_manual(values = c('red', 'darkblue')) + scale_size(range = c(5, 10)) + xlab('Age') + ylab('Hours Spent Online') + ggtitle('Hours Spent Online by Age and Gender') + theme(plot.title = element_text(hjust = 0.5))
bubble_graph
```
